image:
  file: .github/.gitpod.Dockerfile

tasks:
  - name: Test dependencies
    command: |
      source /opt/conda/bin/activate ibbis
      nextflow -version
      nf-core --version
      pytest --version
      echo "Environment is ready!"

  - name: Open terminal
    command: bash

vscode:
  extensions:
    - codezombiech.gitignore
    - esbenp.prettier-vscode
    - EditorConfig.EditorConfig
    - Gruntfuggly.todo-tree
    - nextflow.nextflow
    - streetsidesoftware.code-spell-checker
    - ms-python.python
    - redhat.vscode-yaml
    - ms-toolsai.jupyter

ports:
  - port: 8888
    onOpen: open-preview
    visibility: public